Feat: Present field for work and education
CareerSocius/resumebuilder pull request #137
Opened 2022-03-08 08:02 UTC by kvihashini

# Notion Task

https://www.notion.so/Present-Field-for-Work-and-Education-bce73aee9f4b42bab32e248be82740ee

# Changes Made In This PR

- Added `isPresent` prop in `Input.js`. Prop included in `EducationModal.js`
- TODO:  Handle state of `present`, Fix 'required field' for End Date when present is selected,`WorkModal.js`

# Screenshots

_for UI changes, show a before and after shot_\
**Before:**

**After:**

2022-03-16 02:41 UTC, millasml commented on src/modals/sections/EducationModal.js
> +        .required(t('shared.forms.validation.required')),
since we just check if the date is an empty string and then render it as present if it is, we dont need to update this validation.

2022-03-18 10:37 UTC, millasml requested changes
looks good! just some styling and use it for the WorkModal too.

For the styling of the present button, you realize that setting placement to `end` doesnt work. You need to override the root class of the `FormControlLabel` to have `flex-direction: row`. See it done here:

https://github.com/CareerSocius/resumebuilder/blob/90f0f223229a3938d86857cfe2aa8068f54a124b/src/components/journal/piechart/PieChartActivityPie.tsx#L139

https://github.com/CareerSocius/resumebuilder/blob/90f0f223229a3938d86857cfe2aa8068f54a124b/src/components/journal/piechart/PieChartActivityPie.module.css#L17-L19

2022-03-18 17:12 UTC, millasml approved these changes

2022-03-19 03:52 UTC, raeiho approved these changes

2022-03-19 04:02 UTC, merged