Feat: Add Contact Us Section
CareerSocius/resumebuilder pull request #169
Opened 2022-03-19 08:55 UTC by tharshita

# Notion Task

https://www.notion.so/Contact-Us-option-2513e86d53774960bbb4f203578a4fdd
https://www.notion.so/Hyperlink-to-CareerSocius-Website-4d39818218b346a58f142ff1d8d2d8ed

# Changes Made In This PR

- added hyperlink to website
- added contact us with mailto career socius email

# Screenshots

_for UI changes, show a before and after shot_\
**Before:**
<img width="632" alt="Screenshot 2022-03-19 at 4 55 33 PM" src="https://user-images.githubusercontent.com/46225963/159114615-a5914283-87ef-4a3c-95e0-8ec27ddb4741.png">

**After:**

2022-03-20 05:34 UTC, millasml requested changes
looking good! can we make it such that

- the "About" header is gone?
- the resume builder version tag thing is at the bottom most
- the contact us section is styled exactly the same as the review section

2022-03-26 05:33 UTC, millasml requested changes
close!!

2022-03-26 05:33 UTC, millasml commented on src/constants/leftTabBarSections.js
> +    id: 'contact-us',
lets make this `contactUs`

2022-03-26 06:59 UTC, tharshita commented on src/constants/leftTabBarSections.js
> +    id: 'contact-us',
done!

2022-03-27 12:05 UTC, millasml approved these changes

2022-03-27 12:05 UTC, merged