Feat: Toggle visibility for sections
CareerSocius/resumebuilder pull request #172
Opened 2022-03-20 06:24 UTC by merylseow

# Notion Task

https://www.notion.so/Toggle-Visibility-of-Blocks-65b0e2c0560d42bbb7e74fcc5bbb2682

# Changes Made In This PR

- Changed visible field in redux state
- TODO: Fix bug (when clicking to other templates, there is an error)

# Screenshots

_for UI changes, show a before and after shot_\
**Before:**

**After:**

2022-03-27 12:06 UTC, millasml requested changes
close!

2022-03-27 12:06 UTC, millasml commented on src/components/builder/left/sections/Layout.js
> +  // const renderBlocks = blocks || defaultLayouts[template];
remove this comment please!

2022-03-27 14:21 UTC, tharshita commented on src/components/builder/left/sections/Layout.js
> +  // const renderBlocks = blocks || defaultLayouts[template];
oops done!

2022-03-28 15:27 UTC, millasml approved these changes

2022-04-01 15:59 UTC, merged