Feat: SCurve Pages and Share Modal
CareerSocius/resumebuilder pull request #185
Opened 2022-03-27 10:33 UTC by ydymegan

# Notion Task

[Slide 2 and 3 of S Curve](https://www.notion.so/70204328dfbc4abfa76a39d9c3b50169?v=21f1019a9ecd49b791569d2ce69e5cc7&p=1afed0c902f34651a4bab1d71a7dbcb2)
[Reflection Page of S Curve](https://www.notion.so/70204328dfbc4abfa76a39d9c3b50169?v=21f1019a9ecd49b791569d2ce69e5cc7&p=4351fb66532e45c5b6e884b54cfd588f)
[S Curve's Share Modal](https://www.notion.so/70204328dfbc4abfa76a39d9c3b50169?v=21f1019a9ecd49b791569d2ce69e5cc7&p=f7a1bd7457ee4ef3bf84fed19c128153)

# Changes Made In This PR
- completed remaining pages of SCurve (Slide 2, 3 and the reflection page)
- edited share modal to reflect specific activity's name

# Also In This PR
**- pending edits to the scurve slider**_

# Screenshots
**Slide 2** 
![Screenshot 2022-03-27 at 6 31 25 PM](https://user-images.githubusercontent.com/51395560/160277335-969bd2d8-ee0d-42fd-a704-a600492a0097.png)

**Slide 3**
![Screenshot 2022-03-27 at 6 31 53 PM](https://user-images.githubusercontent.com/51395560/160277353-9f256b23-8dac-45aa-91db-74b1e3ac3373.png)

**Reflection Page**
![Screenshot 2022-03-27 at 6 32 22 PM](https://user-images.githubusercontent.com/51395560/160277370-fa6f58f0-6ccb-418d-bf88-235e757d662e.png)

**Share Modal** 
![Screenshot 2022-03-27 at 6 32 48 PM](https://user-images.githubusercontent.com/51395560/160277380-d87a6373-8f90-4519-b0ca-f27456b721ee.png)

2022-03-27 12:43 UTC, millasml requested changes
thanks for bringing up the SCurveSlider bugs! I should have fixed them already. Do check out the comments!

2022-03-27 12:43 UTC, millasml commented on src/components/journal/sCurve/SCurveSlider.tsx
> +  isInteractive,
**FYI**: Added the `isInteractive` prop, and set it to be `true` by default

2022-03-27 12:43 UTC, millasml commented on src/components/journal/sCurve/SCurveSlider.tsx
> +    (x: number) => ((x - padding) / (width - 2 * padding)) * 100,
**FYI**: this line was the issue, it's a math problem. I had to remove the left padding for the calculations to be accurate

2022-03-27 12:43 UTC, millasml commented on src/components/journal/sCurve/SCurveSlider.tsx
> +      if (x < leftCurve.startPoint.x || x > rightCurve.endPoint.x) return;
**FYI**: this fixes the bug where sometimes, the slider knob dissappears

2022-03-27 12:43 UTC, millasml commented on src/components/journal/sCurve/SCurveSlider.tsx
> +  }, [canvasRef, drawSCurve]);
**FYI**: this fixes the bug where the slider knob is not smooth

2022-03-27 12:43 UTC, millasml commented on src/components/journal/sCurve/slides/SCurveDescription.tsx
> +              )}
to make this cleaner, can you condense this out to a function? something like

```
const getTitleAndDescription = () => {title: string; description: string}
const {title, description} = getTitleAndDescription()
```

then you can just use `title` and `description` here

I also realized that based on the length of the title and descriptions, the height of these headers change and make the s curve jump around. This makes it kinda hard to use the s curve as it moves while im dragging. can you make it a fixed height?

2022-03-27 12:43 UTC, millasml commented on src/components/journal/sCurve/slides/SCurvePlot.tsx
> +  const [stage, setStage] = useState(sCurve?.stage ?? 0);
lets just call this `level` to make it less confusing, its easy to mistake stage for "mastery", "gaining competency" etc....

2022-03-27 12:43 UTC, millasml commented on src/components/journal/sCurve/slides/SCurveDescription.tsx
> +              )}
FYI: i also made the values for ground zero and mastery abit looser ( less than 1 instead of 0, and more than 99 instead of 100) so that they can actually see the descriptions

2022-03-27 12:43 UTC, millasml commented on src/modals/ShareModal.tsx
> +        </p>
maybe make this a prop in the `ShareModal` instead?

2022-04-01 02:32 UTC, xinyitay commented on src/components/journal/sCurve/slides/SCurvePlot.tsx
> +  const [stage, setStage] = useState(sCurve?.stage ?? 0);
to clarify, does this refer to the naming of the local state `stage` in useState here or the redux state `stage` which is also used in slices, sagas, types?

2022-04-04 13:26 UTC, millasml commented
is this ready for my review?

2022-04-06 06:27 UTC, ydymegan commented
> is this ready for my review?

yup! sorry for the delay! i think i might have did something to `package-lock.json` and was trying to revert it! but i think you can review it first! thanks so much! :)

2022-04-06 14:33 UTC, millasml approved these changes

2022-04-06 14:34 UTC, merged