Feat: Added bullet points to tooltips
CareerSocius/resumebuilder pull request #188
Opened 2022-03-29 14:45 UTC by by-bai

# Notion Task

https://www.notion.so/Tooltips-as-Short-Bullet-Points-part-1-7b5b408639bb432e8fdb1df727bbe9ca

# Changes Made In This PR

- updated `generalResumeTips` in en.json
- added ListItemIcon (bullet point) and styled it 

# Screenshots

**After:**
![Screenshot 2022-03-29 at 10 44 35 PM](https://user-images.githubusercontent.com/58441020/160638440-ecc0c1c6-4529-48d6-a068-8ee4abd52a02.png)

2022-04-01 16:21 UTC, millasml requested changes
do you know if you need to do this for `TipGrid` too? mind checking with @raeiho ?

Is is possible to also make the dots aligned to the top? please check with raei regarding this too

2022-04-11 07:22 UTC, millasml requested changes
seems like its not working on the preview site :(
<img width="669" alt="image" src="https://user-images.githubusercontent.com/43376033/162685270-a1069b89-b491-462c-ba0a-8092be858db7.png">

can you move all the tailwind stuff in line 25 to the `root` class? you can use the `@apply`

2022-04-11 13:23 UTC, kvihashini commented
> seems like its not working on the preview site :( <img alt="image" width="669" src="https://user-images.githubusercontent.com/43376033/162685270-a1069b89-b491-462c-ba0a-8092be858db7.png">
> 
> can you move all the tailwind stuff in line 25 to the `root` class? you can use the `@apply`

okay! moving it `root` class fixed the bullets on the preview site, thank you :-)

2022-04-11 16:26 UTC, millasml approved these changes

2022-04-11 16:27 UTC, merged