Feat: Add interim timeline message
CareerSocius/resumebuilder pull request #194
Opened 2022-04-01 13:52 UTC by tsm1820

# Notion Task

https://www.notion.so/Interim-Message-for-empty-timeline-f374a5bd7da64ac682b5f3d1cf9fc146

# Changes Made In This PR

Added interim timeline message

2022-04-01 16:46 UTC, millasml requested changes
looking at the notion, i think there is a bunch more work to do:
<img width="696" alt="image" src="https://user-images.githubusercontent.com/43376033/161306757-6e208d96-ffc9-4f73-855c-d4ba2d611af3.png">

you have to make the fake timeline entry like in there. i suggest you add the `className` prop to `TimelineEntry`, and put it in line 79. After that, you can just use `TimelineEntry` to create that fake one and override the styles easily

2022-04-02 04:49 UTC, gracuamole commented
hi sheehui! don't need to create the fake example timeline entry for this task, as it's in a separate task! sorry for the confusion

2022-04-02 06:12 UTC, millasml commented
thanks for the clarification grace! if that's the case, can we centre it?

<img width="602" alt="image" src="https://user-images.githubusercontent.com/43376033/161369446-e0dc097b-ce18-49e2-8b68-302dce60de1e.png">

2022-04-08 16:56 UTC, millasml requested changes

2022-04-08 16:56 UTC, millasml commented on src/pages/app/timeline.module.css
>  }
you can't do this, as it affects the rest of the h1 items:

<img width="669" alt="image" src="https://user-images.githubusercontent.com/43376033/162487339-51ea24ec-f325-4a65-b4e1-334a6223caf1.png">

2022-04-08 16:56 UTC, millasml commented on src/pages/app/timeline.tsx
> +                  <div>
create a new css class called `emptyTimeline`, and use it in line 186 over here. Over there, you can center the text. revert the text centering you did for h1 and promptMsg

2022-04-09 07:07 UTC, millasml commented
done in https://github.com/CareerSocius/resumebuilder/pull/204

2022-04-11 07:22 UTC, closed without merging