Fix: Modify Tooltips
CareerSocius/resumebuilder pull request #203
Opened 2022-04-08 09:03 UTC by tharshita

# Notion Task
https://www.notion.so/Tooltips-part-2-b30c1f6a59334bcea3d081bac775372a

# Changes Made In This PR

- Modified and added tooltips

# Screenshots

_for UI changes, show a before and after shot_\
**Before:**
<img width="1093" alt="Screenshot 2022-04-08 at 5 02 59 PM" src="https://user-images.githubusercontent.com/46225963/162403114-b06623ee-d84f-4b2c-a17a-123c3fb00c77.png">

**After:**
Example of addition of tooltip for awards:
<img width="851" alt="Screenshot 2022-04-08 at 5 02 19 PM" src="https://user-images.githubusercontent.com/46225963/162403011-d8317750-a0f7-4a86-8b90-793dc91589c2.png">

2022-04-08 17:19 UTC, millasml requested changes
looking good! can we rename `TipGrid` to `WorkExperienceTooltip`, and move it from the shared folder to `src/components/builder/`?

2022-04-08 17:26 UTC, tharshita commented
> looking good! can we rename `TipGrid` to `WorkExperienceTooltip`, and move it from the shared folder to `src/components/builder/`?

Okies done!!

2022-04-09 07:16 UTC, millasml submitted a review, later dismissed

2022-04-13 03:23 UTC, millasml approved these changes

2022-04-13 03:23 UTC, merged