Fix: Rename blocks for CareerSocius General
CareerSocius/resumebuilder pull request #214
Opened 2022-04-10 11:10 UTC by kvihashini

# Notion Task

https://www.notion.so/70204328dfbc4abfa76a39d9c3b50169?v=2db6790b04df468cb2f1e85a6c117567&p=703e464b72114ed4b9286c2d22597e56 

# Changes Made In This PR

- Renamed blocks from 'Block 1' and 'Block 2' to 'Content' and 'Additional Information' if CareerSocius General template is chosen

# Screenshots

**Before:**
![Screenshot 2022-04-10 at 7 05 04 PM](https://user-images.githubusercontent.com/77200805/162615075-62317cb4-7546-4dc3-a3e5-beb759bb4829.png)

**After:**
![Screenshot 2022-04-10 at 6 55 57 PM](https://user-images.githubusercontent.com/77200805/162615010-7ad2583d-9401-4acb-ab2f-d51edb98006b.png)

2022-04-11 07:31 UTC, millasml requested changes
getting an error when i try to choose the general template in the preview link:

<img width="669" alt="image" src="https://user-images.githubusercontent.com/43376033/162686698-a897b7b2-2493-45a9-9e15-1b62fb8d6fdc.png">

2022-04-11 07:32 UTC, millasml commented on src/components/builder/left/sections/Layout.js
> +        throw new Error();
change this line to
```
`${t('builder.layout.block')} ${ind + 1}`
```

2022-04-11 16:30 UTC, millasml requested changes
hmm it doesn't seem to work :( 

<img width="440" alt="image" src="https://user-images.githubusercontent.com/43376033/162787064-4d7dac1a-0fc5-43fc-8c40-16e38545643d.png">

maybe its because your switch case are strings, when ind is probably a number?

2022-04-11 16:30 UTC, millasml commented on src/components/builder/left/sections/Layout.js
> +                      {template === 'wallStreet'
can you use the enum from `TemplateEnum` in `Template.ts`?

2022-04-11 16:30 UTC, millasml commented on src/components/builder/left/sections/Layout.js
> +  const wallStreetLayout = (ind) => {
lets rename this to `getWallStreetBlockName`

2022-04-11 17:07 UTC, kvihashini commented
> hmm it doesn't seem to work :(
> 
> <img alt="image" width="440" src="https://user-images.githubusercontent.com/43376033/162787064-4d7dac1a-0fc5-43fc-8c40-16e38545643d.png">
> 
> maybe its because your switch case are strings, when ind is probably a number?

ah right, that makes sense! will change it, thank you!

2022-04-13 02:40 UTC, millasml approved these changes

2022-04-13 02:41 UTC, merged