Feat: timeline tooltip
CareerSocius/resumebuilder pull request #215
Opened 2022-04-11 12:21 UTC by sheehui

# Notion Task

_put the link to the notion task you're working on here_

# Changes Made In This PR

_outline the main changes made to the codebase in this PR_

# Also In This PR

_write other changes, not related to this ticket, that you might have here_

# Screenshots

_for UI changes, show a before and after shot_\
**Before:**

**After:**

2022-04-13 02:39 UTC, millasml requested changes
can we make the tooltip wider?

2022-04-13 02:39 UTC, millasml commented on src/components/timeline/TimelineEntry.module.css
> +}
instead of creating new classes, you can use CSS selectors such that only divs of a particular class name under `modalTimelineEntry` will be affected.

e.g. instead of .modalEntryTitle, you can do
```
.modalTimelineEntry .timelineEntryTitle {
 font-size: 13px;
  font-weight: bold;
  @apply pb-2;
}
```

2022-04-13 02:39 UTC, millasml commented on src/components/timeline/TimelineEntry.module.css
> +}
this way, you dont have to assign so many classNames in `TimelineEntry`

2022-04-13 03:54 UTC, Neha-5678 commented on src/components/timeline/TimelineEntry.module.css
> +}
right, got it! will work on it, thanks milla

2022-04-15 13:39 UTC, millasml approved these changes

2022-04-15 13:39 UTC, merged