Feat: Added work experience end date tooltip
CareerSocius/resumebuilder pull request #28
Opened 2021-12-29 16:19 UTC by by-bai

# Notion Task

https://www.notion.so/Work-Experience-End-Date-Tooltip-fb27d00fae3a428f82db8957bae7737c

# Changes Made In This PR

- Modified Input component to include "tooltip" prop for rendering tooltip.
- Added tooltip for End Date

# Screenshots

**Before:**
<img width="288" alt="Screenshot 2021-12-30 at 12 17 41 AM" src="https://user-images.githubusercontent.com/58441020/147682401-d41853ed-a589-4886-9c1e-027629ad2445.png">

**After:**
<img width="462" alt="Screenshot 2021-12-30 at 12 15 06 AM" src="https://user-images.githubusercontent.com/58441020/147682176-89d105d2-3f03-4fed-96de-609005b6cb96.png">

2022-01-01 14:05 UTC, millasml requested changes
a few more changes after a discussion in https://github.com/CareerSocius/resumebuilder/pull/29#discussion_r777111658

2022-01-01 14:05 UTC, millasml commented on src/components/shared/Input.js
> +        <span className="flex flex-row gap-1 items-center">
remove `items-center`

2022-01-01 14:05 UTC, millasml commented on src/components/shared/Input.js
> +              </div>
remove the `<div>` wrapping MdInfoOutline

2022-01-02 08:47 UTC, by-bai commented
Made changes as requested and rebased branch!

After:
<img width="397" alt="Screenshot 2022-01-02 at 4 47 15 PM" src="https://user-images.githubusercontent.com/58441020/147870770-562eac48-5c4b-473f-bdf5-719f53ddc1a0.png">

2022-01-02 11:35 UTC, millasml approved these changes
LGTM!

2022-01-02 11:35 UTC, merged