Feat: Added photo not recommended tooltip
CareerSocius/resumebuilder pull request #29
Opened 2021-12-30 10:24 UTC by kvihashini

# Notion Task

https://www.notion.so/Photo-Not-Recommended-Tooltip-2263afb0ace44a8f88b649ab58912451

# Changes Made In This PR

- Modified `Input` component to include "tooltip" prop for rendering tooltip
- Created simple component `makeTipList` to make an MUI List (for multiple points in a tooltip)
- Used `makeTipList` in `photoUpload` to display 'photo not recommended' tooltip

# Also In This PR

- Added Input component to include "itemsalignment" prop to fix alignment between tooltip and input label  

# Screenshots

**Before:**
![Screenshot 2021-12-30 at 6 18 55 PM](https://user-images.githubusercontent.com/77200805/147742906-f51c62ae-ed98-4eae-9f2c-0253ddd749fc.png)

**After:**
![Screenshot 2021-12-31 at 5 31 58 PM](https://user-images.githubusercontent.com/77200805/147846687-b26f221a-ddd3-4185-ba5a-4a2568d61a23.png)

2021-12-31 09:32 UTC, kvihashini commented on src/components/shared/Input.js
> +        <span className={`flex flex-row gap-1 ${itemsalignment}`}>
i put `itemsalignment` as a prop as i tried to use `items-center` initially as it was similar to this [PR](https://github.com/CareerSocius/resumebuilder/pull/28/files), but the label 'Photograph' and the Tooltip icon were out of alignment, so i decided to use `items-start` from `PhotoUpload.js` 

using `items-center`:
![Screenshot 2021-12-30 at 6 20 27 PM](https://user-images.githubusercontent.com/77200805/147815328-a62c5159-8b5b-4a2f-99ca-c7a5ee01c8a2.png)

using `items-start`:
![Screenshot 2021-12-31 at 5 31 58 PM](https://user-images.githubusercontent.com/77200805/147815391-26067dcd-e827-4566-bb5f-7ad5fd5f3be1.png)

2021-12-31 09:34 UTC, kvihashini commented on src/i18n/locales/en.json
> +        "- Photo is generally not recommended so as to reduce any possible biasness based on appearance",
okay, will do!

2021-12-31 09:35 UTC, kvihashini commented on src/components/shared/PhotoUpload.js
> +      </List>
thank you for pointing it out, will edit it accordingly!

2022-01-01 14:03 UTC, millasml requested changes
almost there!

2022-01-01 14:03 UTC, millasml commented on src/components/shared/Input.js
> +        <span className={`flex flex-row gap-1 ${itemsalignment}`}>
ahh i see! I went to investigate your problem and it can be fixed by doing the following:

- removing the <div> wrapping <MdInfoOutline>
- changing size of MdInfoOutline to 12
- removing `itemsalignment` all together. That means that line 60 would look like this: 

```
        <span className="flex flex-row gap-1">
```

i'll go ahead and ask https://github.com/CareerSocius/resumebuilder/pull/28 to do the same

2022-01-01 14:15 UTC, kvihashini commented on src/components/shared/Input.js
> +        <span className={`flex flex-row gap-1 ${itemsalignment}`}>
okay, thank you! that works, but the `<MdInfoOutline>` has to be wrapped with a `<div>` for the Tooltip to appear on hover

2022-01-01 15:48 UTC, millasml requested changes
almost almost there!!!

2022-01-01 15:48 UTC, millasml commented on src/components/shared/Input.js
> +              </div>
remove the `<div>` wrapping MdInfoOutline

2022-01-01 15:56 UTC, millasml approved these changes
LGTM!!

2022-01-01 15:57 UTC, merged