Create type for Timeline in TypeScript
CareerSocius/resumebuilder pull request #36
Opened 2022-01-01 17:39 UTC by tsm1820

# Notion Task

https://www.notion.so/70204328dfbc4abfa76a39d9c3b50169?v=2db6790b04df468cb2f1e85a6c117567&p=b9bec7deee434f4c8a0d92c274b88889

# Changes Made In This PR

Added a new ts file called Timeline.ts where we added types such as User and Timeline.

# Also In This PR

No other changes.

# Screenshots

No UI changes.

2022-01-02 03:22 UTC, millasml requested changes
some tweaks

2022-01-02 03:22 UTC, millasml commented on src/types/Timeline.ts
> +};
we dont create a new User type. Insead, add the `timeline` field to the type in `User.ts`

2022-01-02 03:22 UTC, millasml commented on src/types/Timeline.ts
> +  timelineId: string;
just `id` would do

2022-01-02 03:22 UTC, millasml commented
next time, remember to request a review from me!

2022-01-03 10:54 UTC, tsm1820 commented on src/types/Timeline.ts
> +};
Thank you for the comments Milla! Added the timeline field to User.ts

2022-01-03 10:54 UTC, tsm1820 commented on src/types/Timeline.ts
> +  timelineId: string;
okay, changed to id :)

2022-01-03 11:21 UTC, millasml requested changes
sorry i missed some out!

2022-01-03 11:21 UTC, millasml commented on src/types/User.ts
> +  timeline: string;
make this `timelineId`

2022-01-03 11:21 UTC, millasml commented on src/types/Timeline.ts
> +  };
sorry i think i missed this the previous review, but I don't think this is how you meant for the type to be. What you want is a bunch of activities with a unique id as key. Also, the journals have something called activities too so lets name this "entries". What you should do is first, create the `Entry` type separately:

```
export type Entry = {
    isNew: boolean;
    resourceId: string;
    date: number;
    title: string;
    description: string;
    type: string;
}
```

and then the timeline type should be
```
export type Timeline = {
   id: string;
   entries: { [entryId: string] : Entry}
}
}
```

2022-01-03 11:21 UTC, millasml commented on src/types/Timeline.ts
> +  };
you can read more about index signatures here: https://www.typescriptlang.org/docs/handbook/2/objects.html#index-signatures

2022-01-03 13:29 UTC, tsm1820 commented on src/types/Timeline.ts
> +  };
okay, i get it now, thank you!! just pushed the latest changes :)

2022-01-03 13:38 UTC, millasml approved these changes
LGTM! 

do note to use more descriptive commit messages

2022-01-03 13:39 UTC, merged