Feat: Added work experience summary tooltip
CareerSocius/resumebuilder pull request #40
Opened 2022-01-02 13:53 UTC by by-bai

# Notion Task

https://www.notion.so/Work-Experience-Summary-Tooltip-09004fdfb6c345b0affb2e0c8b7ca11a

# Changes Made In This PR

- Added makeTipGrid component that separates an array of arrays into columns
- Modified Input component: set customWidth - maxWidth to 650 to accomodate tooltips with grid
- Added tooltip for Summary

# Screenshots

**Before:**
![Screenshot 2022-01-02 at 9 52 03 PM](https://user-images.githubusercontent.com/58441020/147877930-17f7f643-0cb0-48f2-aaae-6fcdce94078b.png)

**After:**
![Screenshot 2022-01-02 at 9 47 44 PM](https://user-images.githubusercontent.com/58441020/147877830-f8859a7c-7d1c-4855-a812-7b3192028828.png)

2022-01-02 14:55 UTC, millasml requested changes
some changes! good job so far for this more complex task :)

2022-01-02 14:55 UTC, millasml commented on src/components/shared/Input.js
> +
you shouldn't be using useStyles, because we are already using css modules which does the same thing. See the 
```
 import styles from './Input.module.css';
```
all the styles are written in Input.module.css, and then you can access that style by doing `styles.yourStyleName`

2022-01-02 14:55 UTC, millasml commented on src/components/shared/Input.js
> +              classes={{ tooltip: classes.customWidth }}
do `className = {styles.yourStyleName}. you can cmd + F "styles" to see how this is used in other places

2022-01-02 14:55 UTC, millasml commented on src/utils/makeTipGrid.js
> +import React from 'react';
`.ts` this, as its a new file

2022-01-02 16:05 UTC, by-bai commented on src/utils/makeTipGrid.js
> +import React from 'react';
i've tried making the changes but it's not working well >< 
- css modules: can't seem to access the style properly, not sure if i'm doing anything wrong?
- refactoring as typescript: unsure how to fix the syntax for `makeTipGrid.ts`

broke the code for the .ts file but pushing what i have so far so it's clearer!

2022-01-02 17:35 UTC, millasml requested changes

2022-01-02 17:35 UTC, millasml commented on src/components/shared/Input.js
> +              className={styles.tooltip}
sorry about this, you were right about using classes. changing this to 
```
              classes={{ tooltip: styles.tooltip }}
```
will make this solution work immediately. However, i noticed that this will style all the tooltips, making some of the other tooltips look weird:

before:
<img width="491" alt="image" src="https://user-images.githubusercontent.com/43376033/147883384-d0e0be2c-94e3-4a8e-9d3d-422255cdcce8.png">

after:
<img width="724" alt="image" src="https://user-images.githubusercontent.com/43376033/147883389-cd39fb4d-eec3-4557-ac8e-09f65fc5c8e0.png">

2022-01-02 17:35 UTC, millasml commented on src/components/shared/Input.js
> +              className={styles.tooltip}
to solve this, lets add an optional `largeTooltip` prop (that takes in T/F) to `Input` and only apply the style if it is true

```
classes = { largeTooltip ? { tooltip: styles.tooltip } : undefined }
```

2022-01-02 17:37 UTC, millasml commented on src/utils/makeTipGrid.js
> +import React from 'react';
make it `makeTipGrid.tsx`

<img width="476" alt="image" src="https://user-images.githubusercontent.com/43376033/147884296-0bf9472e-a997-4696-87aa-ceda145c9684.png">

i think you would also have to run `npm i -S @material-ui/styles`

if this is too complicated, its fine! just leave it in js and we can work on it in a different PR

2022-01-02 18:05 UTC, by-bai commented on src/components/shared/Input.js
> +              className={styles.tooltip}
okie done!!

2022-01-02 18:11 UTC, by-bai commented on src/utils/makeTipGrid.js
> +import React from 'react';
i've decided to leave it in js for now.. will take time to absorb this and familiarise myself more with ts before trying again. thanks milla!!!

just some questions i have though if you don't mind:
- why is `GridSpacing`, `GridSize` etc imported and how did you know they are types?
- why is `classes` added as a prop to Grid?

2022-01-03 02:42 UTC, millasml commented on src/utils/makeTipGrid.js
> +import React from 'react';
`GridSpacing` and `GridSize` are the types that `<Grid/>` takes in. Typescript in VSCode will show you the exact type that "spacing" and "xs" takes in.

Ignore classes for now! That's not needed atm

2022-01-03 02:43 UTC, millasml approved these changes

2022-01-03 02:43 UTC, merged