Feat: Added Zety Banking resume template
CareerSocius/resumebuilder pull request #46
Opened 2022-01-06 08:34 UTC by by-bai

# Notion Task

https://www.notion.so/Zety-Banking-Resume-template-6ac2a7798cec4a2884dc82a2949f7b32

# Changes Made In This PR

- Set up new resume template
- Added custom blocks for styling the template
- Added a helper method: `formatDateRangeNumOnly` to format dates as YYYY-MM e.g. 2016-12

# Screenshots

Under Templates: 
<img width="121" alt="Screenshot 2022-01-06 at 4 29 51 PM" src="https://user-images.githubusercontent.com/58441020/148353086-3a2eaece-2462-4d36-bd46-b93e9c88e4ee.png">

<img width="570" alt="Screenshot 2022-01-06 at 4 31 48 PM" src="https://user-images.githubusercontent.com/58441020/148353328-5e38e056-2a23-4041-94d2-b1160a93c035.png">

2022-01-07 03:22 UTC, millasml requested changes
looks really good!

2022-01-07 03:22 UTC, millasml commented on src/components/builder/right/sections/Templates.js
> +      }
since youre done with the template, please take a screenshot and put the png in the `static/images/templates` folder and then use that image here

2022-01-07 03:22 UTC, millasml commented on src/data/initialState.json
> +        ["objective", "work", "education", "certifications", "skills"]
you similarly need to add this line to `demoState.json`

2022-01-07 16:19 UTC, by-bai commented on src/components/builder/right/sections/Templates.js
> +      }
done!

2022-01-07 16:21 UTC, by-bai commented on src/data/initialState.json
> +        ["objective", "work", "education", "certifications", "skills"]
done! what's the purpose of demoState?

2022-01-08 02:32 UTC, millasml approved these changes

2022-01-08 02:33 UTC, millasml commented
approved! please ask your PM to check it out

2022-01-10 14:42 UTC, merged