Feat: Added “create new journal” button for journal
CareerSocius/resumebuilder pull request #47
Opened 2022-01-06 09:21 UTC by xinyitay

# Notion Task
https://www.notion.so/Make-create-new-journal-button-which-leads-to-a-new-page-journal-journalEntry-8bbcd77500614d7d9c82e2be37e8dcb0

# Changes Made In This PR
* updated journal.tsx with "create a journal entry" button, which leads to a new page `/journal/journalEntry`
* updated journal.tsx with a placeholder "do a journaling activity" button
* created journalEntry.tsx file under `src/pages/app`
* added routing for journalEntry in `src/pages/app.js`

# Screenshots
**Before:**
<img width="1279" alt="Screenshot 2021-12-29 at 4 05 20 PM" src="https://user-images.githubusercontent.com/65388923/147640551-5509bc32-37f1-42d8-9991-f8d318219768.png">

**After:**
<img width="1278" alt="Screenshot 2022-01-06 at 5 06 14 PM" src="https://user-images.githubusercontent.com/65388923/148358917-081b3b72-f220-4ec6-8094-7b14e143377c.png">

<img width="1278" alt="Screenshot 2022-01-06 at 5 16 28 PM" src="https://user-images.githubusercontent.com/65388923/148359158-036e8100-ccfd-46e7-be6b-cdc34612372b.png">

2022-01-06 18:09 UTC, millasml requested changes
some comments! looking good though :)

2022-01-06 18:09 UTC, millasml commented on src/pages/app/journal.tsx
>  const Journal = ({ user }) => {
please type `user` with `User`

2022-01-06 18:09 UTC, millasml commented on src/pages/app/journal.tsx
> +    navigate('/app/journal/journalactivities');
to simplify, maybe `/entry` and `/activity`

2022-01-06 18:09 UTC, millasml commented on src/pages/app/journalEntry.tsx
> +const JournalEntry = ({ user }) => {
same comment about user

2022-01-06 18:09 UTC, millasml commented on src/types/Journal.ts
> +  reflection3: string;
hm is there some ui change that requires this?

2022-01-06 18:09 UTC, millasml commented on src/types/Journal.ts
> +  category: string;
i believe this is a dropdown category - you can create an enum and make category that type. see `Template.ts` for inspo

2022-01-07 02:25 UTC, ydymegan commented on src/types/Journal.ts
> +  reflection3: string;
yup! yimei changed the activity for Scurve and now it include 2 additional reflection sections. It can be found [here](https://www.figma.com/file/uq3zx0Yu4zONggjJvo77cr/Resume-Builder?node-id=375%3A2) at Frame 26, 31 and 32.

2022-01-07 02:26 UTC, ydymegan commented on src/types/Journal.ts
> +  category: string;
got it, will do the necessary changes!

2022-01-07 02:35 UTC, xinyitay commented on src/pages/app/journal.tsx
> +    navigate('/app/journal/journalactivities');
for journalentry, the notion ticket required us to redirect to `/journal/journalEntry`, while `/journal/journalactivities` is just a placeholder. in this case, is it alright if we keep `/journalentry`, and change only the `/journalactivity to /activity`?

2022-01-07 02:36 UTC, xinyitay commented on src/pages/app/journal.tsx
>  const Journal = ({ user }) => {
got it! will make the changes

2022-01-07 02:37 UTC, millasml commented on src/types/Journal.ts
> +  reflection3: string;
ahhh i see! lets name them abit more descriptively! maybe `reflection`, `strengthReflection`, `disruptReflection`

2022-01-07 02:41 UTC, ydymegan commented on src/types/Journal.ts
> +  reflection3: string;
okie understand!

2022-01-07 03:30 UTC, millasml commented on src/pages/app/journal.tsx
> +    navigate('/app/journal/journalactivities');
i've discussed this with yimei, the routes will be as follows: https://trycatch-hq.slack.com/archives/C02NV7TTMMH/p1641526155000500

hence, please change it to /entry and /activity!

2022-01-07 03:39 UTC, xinyitay commented on src/pages/app/journal.tsx
> +    navigate('/app/journal/journalactivities');
ok! will change both accordingly, thanks milla!

2022-01-07 07:39 UTC, millasml requested changes
sorry missed these out!

2022-01-07 11:46 UTC, millasml submitted a review, later dismissed

2022-01-07 11:46 UTC, millasml commented on src/types/Journal.ts
> +export type Category = keyof typeof PiechartActivityCategoryEnum;
this should be named PiechartActivityCategory similarly, but you can fix this in the next PR

2022-01-08 08:15 UTC, millasml requested changes

2022-01-08 08:15 UTC, millasml commented on src/pages/app/journalEntry.tsx
> +import React, { useEffect, useState } from 'react';
ah sorry i missed this out! this file should be in a subdirectory called `journal`, and be named `entry` to reflect its route name. I.e. this should be at
`src/pages/app/journal/entry`

2022-01-08 08:15 UTC, millasml commented on src/types/Journal.ts
> +export type Category = keyof typeof PiechartActivityCategoryEnum;
bump on this since you have to make changes

2022-01-08 08:38 UTC, millasml approved these changes
LGTM!

2022-01-08 08:39 UTC, merged