Feat: Add scroll to top arrow in Timeline
CareerSocius/resumebuilder pull request #51
Opened 2022-01-07 10:57 UTC by sheehui

# Notion Task

https://www.notion.so/Bring-to-Top-Arrow-235f5e20f6984900a5e52706c8f9d0dd

# Changes Made In This PR

Added a responsive scroll to top arrow button, which appears when page offset is larger than 0. (i.e. user has scrolled down from the top of the page)

# Screenshots

**Before:**
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/77235338/148534032-f1001fea-16b7-4f2d-9fd8-0521c9e2aad3.png">

**After:**

https://user-images.githubusercontent.com/77235338/148533942-1d8ab102-d6b4-492f-b84f-ad06dd8349b3.mov

2022-01-07 11:55 UTC, millasml requested changes
Good job! Just a comment on how styling shold be done

2022-01-07 11:55 UTC, millasml commented on src/components/ScrollToTop.tsx
> +  const classes = useStyles();
use css modules instead of `classes`. You can see how styles is imported and used in `/src/components/shared/Input`

https://github.com/CareerSocius/resumebuilder/blob/1e6e293ba14a8f1c99b40f7113ae9abd56bd6abc/src/components/shared/Input.js#L10

also please move this component to /shared!

2022-01-07 14:42 UTC, sheehui commented on src/components/ScrollToTop.tsx
> +  const classes = useStyles();
Done!

2022-01-08 02:18 UTC, millasml approved these changes
LGTM!

2022-01-08 02:18 UTC, merged