Feat: Zety management consultant resume template
CareerSocius/resumebuilder pull request #53
Opened 2022-01-07 16:17 UTC by merylseow

# Notion Task

https://www.notion.so/Zety-Management-consultant-resume-template-73b39047afa44757b568f9e08f37c5e5

# Changes Made In This PR

- Created zety management consultant resume template
- Added custom blocks for contact, skills, languages, work and education
- Added helper methods `formatDateRangeZetyExperience` to format date to 'YYYY-MM' for experience block and `formatDateZetyEducation` to format date to 'YYYY' for education block

# Screenshots
Under Templates:
<img width="148" alt="Screenshot 2022-01-08 at 12 14 48 AM" src="https://user-images.githubusercontent.com/71954278/148572831-485f0d7f-258d-4366-bb81-27e04dc70d40.png">

<img width="452" alt="Screenshot 2022-01-08 at 12 16 05 AM" src="https://user-images.githubusercontent.com/71954278/148573027-bce2ef5e-fa50-4e07-8c92-c4b2ef79e55a.png">

2022-01-08 02:29 UTC, millasml requested changes
looking good! just need to abide by styling conventions

2022-01-08 02:29 UTC, millasml commented on src/components/builder/right/sections/Templates.js
> +      zetymanagement: file(relativePath: { eq: "templates/celebi.png" }) {
since youre done with the template, please take a screenshot and put the png in the static/images/templates folder and then use that image here

2022-01-08 02:29 UTC, millasml commented on src/components/builder/templates/ZetyManagement.js
> +      color: '#FFFFFF',
i think you should be using the variables from the data, instead of setting these as constants.
```
          fontFamily: data.metadata.font,
          color: data.metadata.colors.text,
          backgroundColor: data.metadata.colors.background
```

2022-01-08 02:29 UTC, millasml commented on src/components/builder/templates/blocks/Education/EducationB.js
> +  // const { t } = useTranslation();
please remove all comments!

2022-01-08 02:29 UTC, millasml commented on src/components/builder/templates/blocks/Languages/LanguagesC.js
> +        // color: 'rgba(48, 53, 63, 255)',
remove all comments!

2022-01-08 02:29 UTC, millasml commented on src/components/builder/templates/blocks/Languages/LanguagesC.js
> +        // color: 'rgba(48, 53, 63, 255)',
same for the rest of the file

2022-01-08 02:29 UTC, millasml commented on src/components/builder/templates/blocks/Languages/LanguagesC.js
> +        // color: 'rgba(48, 53, 63, 255)',
you shouldn't be styling it in the component itself. Instead. create `LanguagesC.module.css` and import it like how its done in this component:

https://github.com/CareerSocius/resumebuilder/blob/1e6e293ba14a8f1c99b40f7113ae9abd56bd6abc/src/components/shared/Input.js#L10

2022-01-08 02:29 UTC, millasml commented on src/components/builder/templates/blocks/Skills/SkillsB.js
> +
same comment about styling - use css modules

2022-01-08 02:29 UTC, millasml commented on src/components/builder/templates/blocks/Skills/SkillsB.js
> +    <div style={{ width: 230 }}>
do not do inline styling too, everything should be in css modules

2022-01-08 02:29 UTC, millasml commented on src/styles/global.css
> +
move these styles to a module specific to your template

2022-01-08 02:29 UTC, millasml commented on src/styles/global.css
> +
something like `ZetyManagement.module.css`.  also use class names instead of ids

2022-01-08 12:56 UTC, millasml requested changes
It looks good in other than the 2 minor comments I gave! I realized there are very few blocks though, but its cause you followed the template on figma. Do you mind checking with raei if this is okay? basically, with this template, things like "Projects", "Awards" and "Certifications" will never be included. Even if it's not, I'm for merging this PR first once these 2 comments are addressed and then following up after

2022-01-08 12:56 UTC, millasml commented on src/components/builder/templates/ZetyManagement.js
> +          color: data.metadata.colors.text,
add `backgroundColor: data.metadata.colors.background`

2022-01-08 12:56 UTC, millasml commented on src/components/builder/templates/ZetyManagement.js
> +            style={{ backgroundColor: data.metadata.colors.background }}
change this to `backgroundColor: data.metadata.colors.primary`

2022-01-08 13:36 UTC, millasml submitted a review, later dismissed

2022-01-11 09:46 UTC, raeiho submitted a review, later dismissed

2022-01-14 19:40 UTC, millasml approved these changes
was going to merge it but there are conflicts again, rebased it for you guys!

can you also ask raei about the slider? it doesn't make sense with the current skill inputs. We need to ask CareerSocius about whether they want to change the skill inputs to accomodate the slider, or remove the slider totally.

2022-01-14 19:46 UTC, merged