Feat: Added Wall Street Banking Resume Template
CareerSocius/resumebuilder pull request #55
Opened 2022-01-08 07:55 UTC by tharshita

# Notion Task

https://www.notion.so/Wall-Street-Oasis-Entry-level-banking-resume-template-55f3bd200d43497ab33a68afcfdf451f

# Changes Made In This PR

- Set up new resume template
- Added custom blocks for styling the template
- Added a helper method: formatDateShortMonth to format dates as MMM YYY e.g. Jan 2016 & itemCheck to check if item is empty string or undefined

# Screenshots
**Expected:**

<img width="594" alt="Screenshot 2022-01-08 at 3 50 15 PM" src="https://user-images.githubusercontent.com/46225963/148636571-585a4a3d-7cef-44ca-b1db-a85873287c01.png">

**Current:**
<img width="462" alt="Screenshot 2022-01-08 at 3 49 09 PM" src="https://user-images.githubusercontent.com/46225963/148636504-199e291f-490c-4819-8830-315b130fee27.png">

2022-01-08 13:15 UTC, millasml requested changes
overall good attempt, but I think your template is still too similar to onyx and not close enough to the one given. I think the following must be implemented:
- skills, awards, certifications etc. to all take 1 line each like it does in the wall street one. You probably want to use `Grid` for this
- email and number to be under the line on either sides

2022-01-08 13:15 UTC, millasml commented on src/components/builder/templates/blocks/BlocksShared.module.css
> +}
remove this totally. The styling given here seems like it could be implemented in the component itself (e.g. adding a comma after each item of the list can be done with template literals) or it can be implemented with tailwind classses.

2022-01-09 16:06 UTC, tharshita commented on src/components/builder/templates/blocks/BlocksShared.module.css
> +}
okay! I've made the necessary changes according to your comments

2022-01-09 16:38 UTC, millasml approved these changes
Looks amazing! please check with raei and if all is good you can merge it in :)

2022-01-12 05:15 UTC, tharshita commented
> Looks amazing! please check with raei and if all is good you can merge it in :)

I've added the projects component and she says this final one is good!

2022-01-12 08:04 UTC, millasml approved these changes

2022-01-12 08:06 UTC, merged