Feat: Added Zety Data Analyst teplate
CareerSocius/resumebuilder pull request #57
Opened 2022-01-08 15:09 UTC by kvihashini

# Notion Task

https://www.notion.so/70204328dfbc4abfa76a39d9c3b50169?v=21f1019a9ecd49b791569d2ce69e5cc7&p=8706d98ece5a4af5a5f8323907465b91

# Changes Made In This PR

- Set up resume template
- Added custom block versions for styling the template
- Added helper methods: to add a timeline for the template, to format dates as YYYY-MM

# Screenshots

Under Templates: 
![Screenshot 2022-01-08 at 11 03 02 PM](https://user-images.githubusercontent.com/77200805/148649156-9810583c-4d89-42cf-a90d-4772fdacec17.png)

**Expected:**
![Screenshot 2022-01-08 at 11 07 11 PM](https://user-images.githubusercontent.com/77200805/148649287-ea2f9e56-42f3-4a73-afed-706319411e63.png)

**Current:**
![Screenshot 2022-01-08 at 11 02 54 PM](https://user-images.githubusercontent.com/77200805/148649194-f0f14973-28a9-497c-abbb-966d798321c9.png)

2022-01-09 09:43 UTC, millasml requested changes
Good attempt, but some changes have to be made. I think you should create the `TimelineHeading` and `TimelineItem` like i mentioned, that will be used in the blocks you created ( `ContactF`, `EducationB`, `HeadingF` etc.). Do contact me if you don't understand it!

also i think a few changes need to be made to make it look more like the template
- make the timeline dots the colour of the primary color (same as the block at the side)
- make the headings same color as the primary color
- make the timeline line longer such that there is no gaps between the dots and the line
- remove the headings for phone, email, linkedin etc. Also you can just not render the address and anything not in the template for now
- make the dates aligned to the right, not left

2022-01-09 09:43 UTC, millasml commented on package.json
> +    "react-icons": "^3.11.0",
is it possible to keep using the same version?

2022-01-09 09:43 UTC, millasml commented on src/components/builder/right/sections/Templates.js
> +      zetydataanalyst: file(relativePath: { eq: "templates/celebi.png" }) {
since youre done with the template, please take a screenshot and put the png in the static/images/templates folder and then use that image here

2022-01-09 09:43 UTC, millasml commented on src/utils/Timeline.js
> +import React, { useContext } from 'react';
this is a component, and hence shouldn't be in the `utils` folder. The same would apply for `makeTipList` and `makeTipGrid` actually, I'll go ahead and fix that up later. Please convert it into a `.tsx` and put it in `src/components/builder/templates/containers`

2022-01-09 09:43 UTC, millasml commented on src/utils/Timeline.js
> +};
Make this section a file on its own, `TimelineHeading.tsx`. Move the relevant styles to `TimelineHeading.module.css`

2022-01-09 09:43 UTC, millasml commented on src/utils/Timeline.js
> +};
Make this section a file on its own, TimelineItem.tsx. Move the relevant styles to TimelineItem.module.css

2022-01-09 09:43 UTC, millasml commented on src/utils/TimelineItems.js
> +export default TimelineItems;
i don't think this is the right way to do it. Instead of creating this list, why not put the item within the new blocks you created? The blocks can then use `TimelineItem` so that you can just render the blocks in the `Timeline` right at the template. At the same time, use `TimelineHeading` in your Heading block so you can render it nicely too

2022-01-09 09:43 UTC, millasml commented on src/utils/Timeline.js
> +      {heading.items && <MakeTimelineItem section={section} data={data} />}
i dont think making the TimelineItem when the function is TimelineHeading is a good pattern

2022-01-09 09:43 UTC, millasml commented on src/components/builder/templates/ZetyDataAnalyst.js
> +            }}
avoid inline styling - use ccs modules

2022-01-09 09:43 UTC, millasml commented on src/components/builder/templates/ZetyDataAnalyst.js
> +          }}
avoid inline styling - use ccs modules

2022-01-09 09:43 UTC, millasml commented on src/components/builder/templates/ZetyDataAnalyst.js
> +            }}
you can do it like this 
```
className = {`col-span-2 px-6 py-8 ${yourStyle}`}
```

2022-01-09 18:19 UTC, kvihashini commented on package.json
> +    "react-icons": "^3.11.0",
yep, will keep the same version!

2022-01-10 10:46 UTC, kvihashini commented on src/utils/TimelineItems.js
> +export default TimelineItems;
okay, will fix this!

2022-01-11 02:07 UTC, millasml requested changes
Looking really good! Just a few more code hygiene related comments :)

I also noticed that the dots are really small when i run the code;
<img width="452" alt="image" src="https://user-images.githubusercontent.com/43376033/148868739-b220891f-09b4-448f-a426-a3da760c6007.png">

can you look into that too?

2022-01-11 02:07 UTC, millasml commented on src/components/builder/templates/blocks/Heading/HeadingH.js
> +      }}
remove this` <h6>` wrapping

2022-01-11 02:07 UTC, millasml commented on src/components/builder/templates/blocks/Languages/LanguagesC.js
> +    <div>
replace `<div>` with `<>` and `</>`

2022-01-11 02:07 UTC, millasml commented on src/components/builder/templates/blocks/Heading/HeadingH.js
> +      <MakeTimelineHeading section={children} icon={Icon} colour={colour} />
you shouldn't pass in children as props. instead, do 
```
<MakeTimelineHeading icon={Icon} color={color}>{children}</MakeTimelineHeading>
```

2022-01-11 02:07 UTC, millasml commented on src/components/builder/templates/blocks/Projects/ProjectsB.js
> +    <div>
replace `<div>` with `<>` and `</>`

2022-01-11 02:07 UTC, millasml commented on src/components/builder/templates/blocks/Work/WorkB.js
> +    <div>
replace `<div>` with `<>` and `</>`

2022-01-11 02:07 UTC, millasml commented on src/components/builder/templates/containers/MakeTimelineHeading.tsx
> +    <div>
replace `<div>` with `<>` and `</>`

2022-01-11 02:07 UTC, millasml commented on src/components/builder/templates/containers/MakeTimelineHeading.tsx
> +  section,
replace `section` with `children`. `children` will have everything you pass into the component between the `<>` tags

2022-01-11 02:07 UTC, millasml commented on src/components/builder/templates/containers/MakeTimelineItem.tsx
> +import React from 'react';
rename this `TimelineItem`

2022-01-11 05:36 UTC, kvihashini commented on src/components/builder/templates/blocks/Awards/AwardsB.js
> +    <div>
ah okay i understand! will change the rest as well :-)

2022-01-12 14:16 UTC, millasml submitted a review, later dismissed

2022-01-12 14:16 UTC, millasml commented on src/components/builder/templates/ZetyDataAnalyst.js
> +                    return <div>{Component && <Component key={x} />}</div>;
can you change this to 
```
return <Component && <Component key={x} />;
```

2022-01-12 14:30 UTC, kvihashini commented on src/components/builder/templates/ZetyDataAnalyst.js
> +                    return <div>{Component && <Component key={x} />}</div>;
done!

2022-01-12 14:43 UTC, millasml submitted a review, later dismissed

2022-01-14 22:34 UTC, raeiho submitted a review, later dismissed

2022-01-15 06:32 UTC, tharshita approved these changes

2022-01-15 06:32 UTC, merged