Feat: Create Timeline saga template and timeline slice
CareerSocius/resumebuilder pull request #61
Opened 2022-01-12 05:56 UTC by sheehui

# Notion Task

Saga template: https://www.notion.so/Create-template-timelineSaga-2b288a70802e42c6bc647022f6797142
Timeline slice: https://www.notion.so/Create-timelineSlice-with-the-updateTimeline-action-and-shouldUpdateTimeline-property-in-the-state-215c5eb201334b0ba6bbeda335a5e6b7

# Changes Made In This PR

- Create template for timeline sagas
- Add timeline slice with updateTimeline action

# Screenshots

no UI changes

2022-01-13 11:52 UTC, millasml requested changes
looking great!

2022-01-13 11:52 UTC, millasml commented on src/redux/slices/timelineSlice.ts
> +      state.shouldUpdateTimeline = action.payload.isUpdating;
shouldUpdateTimeline seems to have a different meaning form isUpdating. isUpdating means that it is currently updating, whereas shouldUpdateTimeline kinda implies that the updates in this state are not yet pushed to the database hence `shouldUpdateTimeline` is the flag that indicates whether the database needs to be updated or not. I think shouldUpdateTimeline is accurate, so please create a new payload type (something like ShouldUpdatePayload)

2022-01-13 11:52 UTC, millasml commented on src/data/initialTimelineState.json
> +}
can you make this typescript, and with type `Timeline`?

2022-01-13 15:02 UTC, sheehui commented on src/redux/slices/timelineSlice.ts
> +      state.shouldUpdateTimeline = action.payload.isUpdating;
done [@cdd180e](https://github.com/CareerSocius/resumebuilder/pull/61/commits/cdd180e3b7d015fa36fdc60069229af6647336e4)

2022-01-13 16:05 UTC, millasml requested changes

2022-01-13 16:05 UTC, millasml commented on src/redux/types/timelineState.ts
> +  shouldUpdateTimeline: boolean;
you can just name this `shouldUpdate`, because it is already in the timeline state you dont need to specify that again

2022-01-13 16:05 UTC, millasml commented on src/redux/types/payloads.ts
> +  shouldUpdateTimeline: boolean;
you can just name this `shouldUpdatePayload`

2022-01-13 16:05 UTC, millasml commented on src/data/initialTimelineState.ts
> +export default initialTimelineState;
since its so simple, i think you can just not have this file and put it in the redux timelineState

2022-01-14 06:46 UTC, millasml approved these changes

2022-01-14 11:05 UTC, merged