Feat: Setup of Activities Landing Page
CareerSocius/resumebuilder pull request #63
Opened 2022-01-12 16:15 UTC by ydymegan

# Notion Task
**UI Buttons & Description:** https://www.notion.so/UI-buttons-description-f966604b595c475b992a2b96f5aed4dd
**3 Buttons Link To Respective Activities:** https://www.notion.so/3-buttons-link-to-respective-activities-8637efcb63504514a0b135774a8a34bc

# Changes Made In This PR
- created the landing page for journal activities and displayed 3 activities and its description in cards
- images are the same (for now) as we are pending images from careersocious
- edited `en.json` with raw texts for the journal activities landing page
- included routing for the individual activities 

# Screenshots
**Before:**
None, pages were newly created.

**After:**
![Screenshot 2022-01-13 at 12 12 05 AM](https://user-images.githubusercontent.com/51395560/149178129-12aac972-ec60-4025-926d-71a5e3b6f964.png)
![Screenshot 2022-01-13 at 12 12 13 AM](https://user-images.githubusercontent.com/51395560/149178139-de1f4757-ccf3-459b-b6a6-2ada790d868b.png)
![Screenshot 2022-01-13 at 12 12 20 AM](https://user-images.githubusercontent.com/51395560/149178152-3f644934-da0d-4ba2-af2f-05356d3159a5.png)
![Screenshot 2022-01-13 at 12 12 29 AM](https://user-images.githubusercontent.com/51395560/149178170-c65f6db0-b3cc-443e-a2d6-5abcc08b56ea.png)
![Screenshot 2022-01-13 at 12 12 39 AM](https://user-images.githubusercontent.com/51395560/149178183-5178579d-c16d-4ff0-80db-120f52917495.png)

2022-01-13 12:58 UTC, millasml requested changes

2022-01-13 12:58 UTC, millasml commented on package.json
> +    "install": "^0.13.0",
what is this for? I don't see it used anywhere

2022-01-13 12:58 UTC, millasml commented on src/pages/app/journal/activity.tsx
> +// import piechartimage from '../../../../static/images/activities/piechart.png';
remove comments

2022-01-13 12:58 UTC, millasml commented on src/pages/app/journal/activity.tsx
> +            {t('activity.landingPage.header1')}
Do you think you can use the `Grid` component from material UI instead? This will make sure that the cards are reasonably sized even in a small screen and automatically re layout everything

2022-01-13 17:30 UTC, ydymegan commented on src/pages/app/journal/activity.tsx
> +// import piechartimage from '../../../../static/images/activities/piechart.png';
we left it there because we are pending images from careersocius side, do we remove this entirely and add back later?

2022-01-13 17:31 UTC, ydymegan commented on package.json
> +    "install": "^0.13.0",
not rlly sure about this! sorry!! may have accidentally installed something, may i ask if it would be resolved by removing that line?

2022-01-14 04:10 UTC, ydymegan commented on src/pages/app/journal/activity.tsx
> +            {t('activity.landingPage.header1')}
also to clarify! @millasml do i also include the headings into the Grid or just the card? thank you!

2022-01-14 06:53 UTC, millasml commented on package.json
> +    "install": "^0.13.0",
you have to remove it from package-lock.json too, so you should use npm uninstall <packagename>

2022-01-14 06:53 UTC, millasml commented on src/pages/app/journal/activity.tsx
> +// import piechartimage from '../../../../static/images/activities/piechart.png';
yup

2022-01-14 06:53 UTC, millasml commented on src/pages/app/journal/activity.tsx
> +            {t('activity.landingPage.header1')}
you can include the headings too!

2022-01-14 13:21 UTC, millasml requested changes

2022-01-14 13:21 UTC, millasml commented on src/pages/app/journal/activity.tsx
> +        <Grid item xs={3}>
`lg = {3}`

2022-01-14 13:21 UTC, millasml commented on src/pages/app/journal/activity.tsx
> +        <Grid item xs={3}>
`lg = {3}`

2022-01-14 13:21 UTC, millasml commented on src/pages/app/journal/activity.tsx
> +        <Grid item xs={3}>
`lg = {3}`

2022-01-14 19:23 UTC, millasml approved these changes

2022-01-14 19:23 UTC, merged