Feat: Journal Entry Autosave Function
CareerSocius/resumebuilder pull request #74
Opened 2022-01-20 14:56 UTC by ydymegan

# Notion Task

**Autosave Function:** https://www.notion.so/70204328dfbc4abfa76a39d9c3b50169?v=21f1019a9ecd49b791569d2ce69e5cc7&p=a44a40ec1d7b4ef2bb1d19193410742e

# Changes Made In This PR
- created updated and get journal entry api
- created redux hooks and slices
- included the redux saga 
- added the "Last Modified" column

# Screenshots
When we first press on "Create a journal entry", an entry is created 
![Screenshot 2022-01-20 at 10 52 22 PM](https://user-images.githubusercontent.com/51395560/150362364-29f9e0a2-5874-4705-84b1-2180a893ebb3.png)

And any changes made is automatically saved into the database
![Screenshot 2022-01-20 at 10 53 20 PM](https://user-images.githubusercontent.com/51395560/150362496-c4605f87-1fe9-46f9-99d2-e2e72c74a9b0.png)

We can access the journal entry again with the specific id in the url
![Screenshot 2022-01-20 at 10 54 43 PM](https://user-images.githubusercontent.com/51395560/150362748-bf37ce22-5795-4baf-9e62-85cbf16fd41e.png)

2022-01-21 02:44 UTC, millasml requested changes

2022-01-21 02:44 UTC, millasml commented on src/api/journal/createJournalEntry.ts
>      updatedAt: newCreatedAt as number,
`updatedAt` should always be `firebase.database.ServerValue.TIMESTAMP`

2022-01-21 02:44 UTC, millasml commented on src/pages/app/journal/entry.tsx
> +    navigate('/app/journal');
why not -1?

2022-01-21 02:44 UTC, millasml commented on src/pages/app/journal/entry.tsx
> +  const firstUpdate = useRef(true);
i dont think you can use a ref, as the ref value will persist throughout the components lifetime. So if your component rendered once with id1, then you will set it to false. Then after that, if you visit another journal entry with id2, the ref value will stay false and the point of your ref (which is to detect whether its the component’s first update) will be lost

2022-01-21 02:44 UTC, millasml commented on src/pages/app/journal/entry.tsx
> +  }, [title, content, createdAt, jid, updatedAt]);
why cant we just use check if loading === true? because right now, loading is only true until we finish fetching the data and then set it to false

2022-01-22 04:54 UTC, xinyitay commented on src/api/journal/createJournalEntry.ts
>      updatedAt: newCreatedAt as number,
ok! will make the changes accordingly

2022-01-22 05:02 UTC, xinyitay commented on src/pages/app/journal/entry.tsx
> +    navigate('/app/journal');
at the moment, if we click submit, the page is redirected to a URL that includes the title query parameter. we found that if we used -1, it will redirect to the `app/journal/entry` page which creates a new entry again, so we tried to bypass this by redirecting to the `app/journal` directly!

<img width="1280" alt="Screenshot 2022-01-22 at 12 58 40 PM" src="https://user-images.githubusercontent.com/65388923/150625321-f61be24c-e0c4-4d4b-862f-5d0413fdc850.png">

2022-01-22 05:11 UTC, ydymegan commented on src/pages/app/journal/entry.tsx
> +  }, [title, content, createdAt, jid, updatedAt]);
we've changed it to that instead of the ref!

2022-01-23 13:11 UTC, millasml requested changes
really small changes, great job!!

2022-01-23 13:11 UTC, millasml commented on src/pages/app/journal/entry.tsx
> +            defaultValue={title}
this is called a controlled element. Hence, you  have to use `value` instead of `defaultValue` 

Read more here: https://reactjs.org/docs/forms.html#controlled-components

this applies to all the form fields

2022-01-23 13:11 UTC, millasml commented on src/redux/slices/journalEntrySlice.ts
> +export const JOURNAL_ENTRY_SLICE_KEY = 'journalentry';
lets use camel case, so `journalEntry`

2022-01-23 13:11 UTC, millasml commented on src/redux/store.ts
> +    journalentry: journalEntryReducer,
camel case, `journalEntry`

2022-01-23 15:16 UTC, xinyitay commented on src/pages/app/journal/entry.tsx
> +            defaultValue={title}
ok! made the necessary changes

2022-01-24 06:29 UTC, millasml approved these changes

2022-01-24 07:09 UTC, merged