Feat: Made extractTimelineEntryUpdates utility function
CareerSocius/resumebuilder pull request #76
Opened 2022-01-21 04:00 UTC by Neha-5678

# Notion Task

https://www.notion.so/create-the-extractTimelineEntryUpdates-utility-function-that-looks-that-the-payload-of-addResumeItem-2cf460a8efeb4648909293375409be8a

# Changes Made In This PR

_outline the main changes made to the codebase in this PR_

# Also In This PR

_write other changes, not related to this ticket, that you might have here_

# Screenshots

_for UI changes, show a before and after shot_\
**Before:**

**After:**

2022-01-21 09:43 UTC, millasml requested changes
i think you definitely need to use an array to store the updates

2022-01-21 09:43 UTC, millasml commented on src/redux/sagas/resumeSaga.ts
> +import extractTimelineEntryUpdates from '../../utils/extractTimelineEntryUpdates';
lets not import it first, so that the linter will not complain about an unused import

2022-01-21 09:43 UTC, millasml commented on src/utils/extractTimelineEntryUpdates.ts
> +  currentItems,
type these arguments too

2022-01-21 09:43 UTC, millasml commented on src/utils/extractTimelineEntryUpdates.ts
> +  const prevItemsMap = {};
lets use the javascript `Map` object instead: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

2022-01-21 09:43 UTC, millasml commented on src/utils/extractTimelineEntryUpdates.ts
> +  let updatedItem = null;
i used an update array because you might have multiple edits for an item array. e.g. you can edit one entry, and add one entry, and both should be reflected. doing it like this limits that

2022-01-21 09:43 UTC, millasml commented on src/utils/extractTimelineEntryUpdates.ts
> +      updateString = 'Work Experience updated.';
maybe you can be more descriptive on which work experience is updated, like what you did for the `add` one?

2022-01-21 09:43 UTC, millasml commented on src/utils/extractTimelineEntryUpdates.ts
> +  return updateString;
be more descriptive in general for the update strings

2022-01-21 09:43 UTC, millasml commented on src/utils/extractTimelineEntryUpdates.ts
> +  currentItems,
are these resume items, or are you going to take in the entire resume?

2022-01-21 11:34 UTC, Neha-5678 commented on src/utils/extractTimelineEntryUpdates.ts
> +  currentItems,
Thank you for the comments milla! These arguments are resume items aka ResumeSection<T>, but T could be Work Experience, Education, Skills or Certification. I am unsure which type to indicate because there isn't a general type that encompasses all these different types.

2022-01-21 13:46 UTC, millasml commented on src/utils/extractTimelineEntryUpdates.ts
> +  currentItems,
i was wondering why we are taking the individual items instead of the entire resume object?

2022-01-22 02:18 UTC, millasml approved these changes

2022-01-22 02:19 UTC, merged