Feat: Created WPLH Dashboard
CareerSocius/resumebuilder pull request #81
Opened 2022-01-29 08:38 UTC by xinyitay

# Notion Task

https://www.notion.so/WPLH-dashboard-675cd8c5ccbe4284ab6b5157ecfa99ae

# Changes Made In This PR
 * added createWPLH api
 * added SlideOne and SlideTwo components with css modules (UI to be updated)
 * updated `en.json` with SlideOne and SlideTwo titles and description
 * updated WPLH component with conditional rendering
 * created WPLH redux slice
 * updated WPLH type in `journal.ts`
 * added WPLH SlideOne images

# Screenshots

**Before:**
<img width="1279" alt="Screenshot 2022-01-29 at 4 34 51 PM" src="https://user-images.githubusercontent.com/65388923/151654082-bf60723e-e069-4608-8ddc-95a74b489b2e.png">

**After:**
<img width="1278" alt="Screenshot 2022-01-29 at 4 36 06 PM" src="https://user-images.githubusercontent.com/65388923/151654116-a85f730d-0dad-4e61-b125-bb059db1aa45.png">
<img width="1280" alt="Screenshot 2022-01-29 at 4 37 15 PM" src="https://user-images.githubusercontent.com/65388923/151654164-7746bacb-42a4-4e03-9aa7-e0b62b6298da.png">

2022-01-29 10:57 UTC, millasml reviewed
looking good!!

2022-01-29 10:57 UTC, millasml commented on src/api/journal/createWPLH.ts
> +import firebase from 'gatsby-plugin-firebase';
can we put this in `src/api/journal/wplh/createWPLH` instead?

2022-01-29 10:57 UTC, millasml commented on src/api/journal/createWPLH.ts
> +    healthLevel: healthLevel,
these variable names are same as the key names, so you can used the shorthand:

```
 const WPLH: WPLHDashboard = {
    id,
    user: user.uid,
    createdAt: firebase.database.ServerValue.TIMESTAMP as number,
    workLevel,
    playLevel,
    loveLevel,
    healthLevel,
...
```

2022-01-29 10:57 UTC, millasml commented on src/types/Journal.ts
>    healthLevel: number;
since this is a number from 1 - 4, you can create a type that reflects that so that it rejects numbers that are more than 4, and use this type everywhere

2022-01-29 10:57 UTC, millasml commented on src/redux/types/payloads.ts
> +};
lets call this `ReflectionPayload`, and use it for the reflections of all activities!

2022-01-29 10:57 UTC, millasml commented on src/redux/slices/wplhSlice.ts
> +);
lets call these `WPLHUpdate ...... ` and call it whenever you want to update. i.e. we are implementing the autosave immediately

2022-01-29 10:57 UTC, millasml commented on src/pages/app/journal/activity/wplh.tsx
> +import SlideTwo from '../../../../components/journal/wplh/slide/SlideTwo';
oops this is my fault and also just a nitpick, can we call the directory `slides` instead of `slide`?

2022-01-30 05:56 UTC, xinyitay commented on src/api/journal/createWPLH.ts
> +import firebase from 'gatsby-plugin-firebase';
ok!

2022-01-30 05:56 UTC, xinyitay commented on src/api/journal/createWPLH.ts
> +    healthLevel: healthLevel,
ahh understand! will make the changes accordingly:)

2022-01-30 05:57 UTC, xinyitay commented on src/redux/types/payloads.ts
> +};
ok!

2022-02-05 04:17 UTC, millasml requested changes
you can just change the styling and i'll approve it. Go ahead and work on the other parts in your next PR!

2022-02-05 04:17 UTC, millasml commented on src/components/journal/wplh/Bar.tsx
> +})(Slider);
please do not use `withStyles`! use css modules, and then override the styles of the Slider with the `classes` prop. you can see how its done here: 

https://github.com/CareerSocius/resumebuilder/blob/bc4a3ed215ddc7c89a9ba43a0e418ad8e7604bf0/src/components/shared/Input.js#L72

2022-02-05 04:17 UTC, millasml commented on src/components/journal/wplh/Bar.tsx
> +const Bar = ({ workLevel, setWorkLevel }) => {
you should accept an `isInteractive` prop, that allows you to choose whether you can change the values of the bar.

you don't need `workLevel` and `setWorkLevel` here - instead you should be using the values from the redux slice. However, its ok to just do the UI first for now

2022-02-05 04:17 UTC, millasml commented on src/redux/slices/wplhSlice.ts
> +  'WPLHAddWorkLevel',
the string here should be the same as the variable name

2022-02-05 04:48 UTC, xinyitay commented on src/redux/slices/wplhSlice.ts
> +  'WPLHAddWorkLevel',
ahh sorry missed this out! will update accordingly, thank you!!

2022-02-05 04:56 UTC, xinyitay commented on src/components/journal/wplh/Bar.tsx
> +})(Slider);
ok!

2022-02-08 03:17 UTC, millasml approved these changes

2022-02-08 03:17 UTC, merged