Feat: Create timeline page layout
CareerSocius/resumebuilder pull request #85
Opened 2022-02-01 06:37 UTC by tsm1820

# Notion Task

https://www.notion.so/Timeline-page-layout-cf2238dc5e6443bf9ded91c83478129e

# Changes Made In This PR

-Created a layout for the timeline page
-Added placeholders for diff resume and journal components
-Made the timeline component independently scrollable

2022-02-02 14:49 UTC, millasml commented on src/pages/app/timeline.tsx
> +              ]}
can you clean this up by making a constant variable on top (right after the imports) called `const MOCK_TIMELINE_ENTRIES`, and then using `MOCK_TIMELINE_ENTRIES` here?

2022-02-02 14:51 UTC, millasml requested changes
this looks pretty close, but i think it needs more padding. also make the items in the Grid item  centered, you can do it by making the items `display: flex` and `justify-content: center`

2022-02-03 11:16 UTC, millasml requested changes

2022-02-03 11:16 UTC, millasml commented on src/components/timeline/Timeline.module.css
> +}
your styles should also be in `./src/pages/app/timeline.module.css`, since the components you are styling is not in `Timeline` anymore

2022-02-03 11:16 UTC, millasml commented on src/pages/app/timeline.tsx
> +};
you should be moving all the entries into an array here, with type `Entry[]`. also please make sure the types are accurate - i think date should be a number

2022-02-03 11:16 UTC, millasml commented on src/pages/app/timeline.tsx
>        <ScrollToTop />
scroll to top should be for the timeline

2022-02-03 11:16 UTC, millasml commented on src/pages/app/timeline.tsx
>      <div>
this div is not needed

2022-02-03 11:16 UTC, millasml commented on src/pages/app/timeline.tsx
> -      <Grid container>
make this grid take the entire screen height, and make overflow hidden

2022-02-04 03:38 UTC, Neha-5678 reviewed
I have looked through and understand the changes made! Thank you milla :)

2022-02-04 06:27 UTC, Neha-5678 approved these changes

2022-02-05 04:19 UTC, millasml approved these changes

2022-02-05 04:19 UTC, merged