Feat: create selection bar with filter
CareerSocius/resumebuilder pull request #86
Opened 2022-02-01 08:11 UTC by sheehui

# Notion Task

[_put the link to the notion task you're working on here_](https://www.notion.so/Create-components-97814a399199442189146e17b72f81a5)

# Changes Made In This PR

- Add dummy search bar
- Add filter function

# Screenshots

_for UI changes, show a before and after shot_\
**Before:**

**After:**
<img width="519" alt="image" src="https://user-images.githubusercontent.com/77235338/151933331-2cd2fcdf-8b21-44a0-9d9c-730a375ae2d7.png">
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/77235338/151933208-eb9854ab-f39b-446a-919e-1d3f2ac21953.png">
<img width="1402" alt="image" src="https://user-images.githubusercontent.com/77235338/151933238-29fb7e3d-ef2c-445b-acdb-a58cf0166add.png">
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/77235338/151933267-9c4cf1c9-12ae-4d7f-ab85-6bde044a255e.png">
<img width="1402" alt="image" src="https://user-images.githubusercontent.com/77235338/151933290-04025b26-f879-4736-a5c6-3e081254f98a.png">

2022-02-02 03:46 UTC, millasml requested changes
why are there changes to package-lock.json when there isn't changes to package.json?

2022-02-02 03:46 UTC, millasml commented on src/components/timeline/Timeline.tsx
> +
you should be creating a separate component for this, maybe something called `SelectionBar`. The `Timeline` component should have the `Timeline` only

2022-02-02 03:46 UTC, millasml commented on src/components/timeline/Timeline.tsx
> +  const [showAll, setShowAll] = useState(true);
why do you need a separate state for `showAll`, when it can just be a flag in `dropdownType`?

2022-02-02 03:46 UTC, millasml commented on src/components/timeline/Timeline.tsx
> +  const [dropdownType, setDropdownType] = useState('All');
`const [dropdownType, setDropdownType = useState<EntryType | "all">("all");`

2022-02-02 03:46 UTC, millasml commented on src/components/timeline/Timeline.tsx
> +    if (type === 'journal') {
`if (type === EntryTypeEnum.journal)`

2022-02-02 03:46 UTC, millasml commented on src/components/timeline/Timeline.tsx
> +      </div>
you should use the material ui component, you can see how the journal team did it here:
https://github.com/CareerSocius/resumebuilder/pull/67/files#diff-2967f8fd976a8a0e330795af36ffe1f8170ab3995bb75bf4cb9a1591d4653d79R1

2022-02-02 03:46 UTC, millasml commented on src/components/timeline/Timeline.tsx
> +          <input className={searchInput} placeholder="Search" />
use textfield from mui: https://github.com/CareerSocius/resumebuilder/pull/67/files#diff-2967f8fd976a8a0e330795af36ffe1f8170ab3995bb75bf4cb9a1591d4653d79R1

2022-02-02 06:23 UTC, sheehui commented
> why are there changes to package-lock.json when there isn't changes to package.json?

it's quite odd because every time i try to update my local `node_modules` it would restructure the entire package.json, i'll revert this file

2022-02-02 06:24 UTC, sheehui commented on src/components/timeline/Timeline.tsx
> +      </div>
done!

2022-02-02 06:24 UTC, sheehui commented on src/components/timeline/Timeline.tsx
> +          <input className={searchInput} placeholder="Search" />
done!

2022-02-02 06:24 UTC, sheehui commented on src/components/timeline/Timeline.tsx
> +    if (type === 'journal') {
done!

2022-02-02 06:24 UTC, sheehui commented on src/components/timeline/Timeline.tsx
> +  const [dropdownType, setDropdownType] = useState('All');
done!

2022-02-02 06:24 UTC, sheehui commented on src/components/timeline/Timeline.tsx
> +  const [showAll, setShowAll] = useState(true);
noted!

2022-02-02 06:24 UTC, sheehui commented on src/components/timeline/Timeline.tsx
> +
done!

2022-02-02 15:20 UTC, millasml requested changes
sorry my bad, did the preview review in a rush 😅

2022-02-02 15:20 UTC, millasml commented on src/components/timeline/Timeline.tsx
> +      </div>
sorry i missed this earlier - you should be using `filter` instead. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

2022-02-02 15:20 UTC, millasml commented on src/components/timeline/Timeline.tsx
> +  const [dropdownType, setDropdownType] = useState<EntryType | 'all'>('all');
sorry i was wrong about this, please do
```
  const [dropdownType, setDropdownType] = useState<DropdownTypeEnum>(
    DropdownTypeEnum.all,
  );
```

2022-02-02 15:20 UTC, millasml commented on src/components/timeline/Timeline.tsx
lets create a `DropdownTypeEnum`

```
export enum DropdownTypeEnum {
  all = 'all',
  activity = 'activity',
  journal = 'journal',
  resume = 'resume',
}
```

2022-02-02 15:20 UTC, millasml commented on src/components/timeline/Timeline.tsx
> +      return 'entries';
`return DropdownTypeEnum.journal`

2022-02-02 15:20 UTC, millasml commented on src/components/timeline/Timeline.tsx
> +      return 'resume';
```
return DropdownTypeEnum.resume

```

2022-02-02 15:20 UTC, millasml commented on src/components/timeline/Timeline.tsx
> +    return 'activities';
```
return DropdownTypeEnum.activity
```

2022-02-02 15:20 UTC, millasml commented on src/components/timeline/Timeline.tsx
> +      </div>
```
        {entries.filter((entry) => {
          if (
            dropdownType === DropdownTypeEnum.all ||
            getDropdownType(entry.type) === dropdownType
          ) {
            return true;
          }
          return false;
        })}
```

2022-02-05 05:05 UTC, millasml requested changes
small change!

2022-02-05 05:05 UTC, millasml commented on src/components/timeline/SelectionBar.tsx
> +          <MenuItem value={DropdownTypeEnum.resume}>Resume</MenuItem>
use i18n

2022-02-05 06:18 UTC, sheehui commented
Updated PR #95

2022-02-05 06:18 UTC, closed without merging