Feat: Create margins and slider
CareerSocius/resumebuilder pull request #87
Opened 2022-02-01 12:30 UTC by kvihashini

# Notion Task

https://www.notion.so/70204328dfbc4abfa76a39d9c3b50169?v=21f1019a9ecd49b791569d2ce69e5cc7&p=842c47e645ce444a9c7dc0c4609f636e

# Changes Made In This PR

- Added Margins section
- Added sample slider and buttons
- TODOs: Handle slider change for buttons, handle margin change when slider is modified, keep slider value constant when navigating between different sections

# Screenshots

_for UI changes, show a before and after shot_\
**Before:**

**After:**

2022-02-02 15:22 UTC, millasml commented
just checking this out prematurely, the margin slider doesn't work yet right?

2022-02-02 15:25 UTC, millasml commented on src/components/builder/left/sections/Margins.js
> +const marks = [
since this is a constant, it has to be all caps so `MARKS`

2022-02-02 15:52 UTC, millasml requested changes
lets create a separate `MarginSlider` component, so that you can use the same component for all 4 sliders

I think its better if we use the example given in material-ui: 
https://v4.mui.com/components/slider/#slider-with-input-field

<img width="299" alt="image" src="https://user-images.githubusercontent.com/43376033/152186831-97f1b094-35a3-4a31-a444-d11e2a45345c.png">

you can see the codesandbox code:
https://codesandbox.io/s/material-demo-forked-30o4e?file=/demo.tsx

and to make sure the value that they give you is always valid, you can edit the `handleInputChange` function in the codesandbox code to fit our needs:
```
  const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setValue(event.target.value === "" ? "" : Math.floor(Number(event.target.value) /2 ) * 2);
  };
```

also make sure to make the slider fit your needs with  `min={2}`, `max={18}`, `step={2}` and `marks` and update the `onBlur` function to reflect our range

2022-02-02 15:52 UTC, millasml commented on src/components/builder/left/sections/Margins.js
> +              marks={marks}
i think setting `marks = {true}` is good enough? i dont think you need to explicitly write all the values

2022-02-02 15:52 UTC, millasml commented on src/components/builder/left/sections/Margins.js
> +const marks = [
since this is a constant, it has to be all caps so `MARKS`

2022-02-02 15:52 UTC, millasml commented on src/components/builder/left/sections/Margins.js
> +  const [value, setValue] = React.useState(10);
you should set this value to the margin value of the resume, with you can get using a selector like how its done in `List.js`

https://github.com/CareerSocius/resumebuilder/blob/befe16c17195168f42facabdca396baaddaf7b0c/src/components/builder/lists/List.js#L26

2022-02-02 15:56 UTC, millasml commented on src/constants/marginOptions.js
> +export const fontSizeOptions = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
im not too sure yet, but it might be better to define these in terms of `min`, `max` and `step`

2022-02-03 02:08 UTC, kvihashini commented
> just checking this out prematurely, the margin slider doesn't work yet right?

the slider works only in the zety data analyst template so far to change the line spacing! will include the margins and font size sliders and update the other templates as well 👍🏽

2022-02-03 07:14 UTC, kvihashini commented on src/components/builder/left/sections/Margins.js
> +  const [value, setValue] = React.useState(10);
ah okay! will change it accordingly 👍🏽

2022-02-03 15:31 UTC, by-bai commented
added font size scaling for ZetyBanking template. 
- added `fontSizeOptions` which helps to convert the font size values from tailwindcss to px (e.g. text-xs = 0.75rem = 0.75*16 = 12px)
- added overriding `style` prop to calculate new font size = slider value + fontSizeOptions['//current fontsize style//']

only implemented on ZetyBanking template for now as i'm not sure whether this is a decent way to handle it or is it too manual?

2022-02-05 05:28 UTC, millasml reviewed
looking good so far!

2022-02-05 05:28 UTC, millasml commented on src/components/shared/MarginSlider.tsx
> +    setValue(Number(event.target.value));
setValue(event.target.value === "" ? "" : Math.floor(Number(event.target.value) /sliderSection.step ) * sliderSection.step);

2022-02-05 05:29 UTC, millasml commented
> added font size scaling for ZetyBanking template.
> 
>     * added `fontSizeOptions` which helps to convert the font size values from tailwindcss to px (e.g. text-xs = 0.75rem = 0.75*16 = 12px)
> 
>     * added overriding `style` prop to calculate new font size = slider value + fontSizeOptions['//current fontsize style//']
> 
> 
> only implemented on ZetyBanking template for now as i'm not sure whether this is a decent way to handle it or is it too manual?

this is the correct way to do it!

2022-02-15 13:57 UTC, millasml submitted a review, later dismissed
approving this for now!!! code is great but we might need to let the margins go to zero because some templates just don't work with margins

2022-02-18 13:42 UTC, millasml approved these changes

2022-02-18 13:42 UTC, merged