Feat: Implement colour wheel
CareerSocius/resumebuilder pull request #93
Opened 2022-02-05 02:27 UTC by merylseow

# Notion Task

https://www.notion.so/Customisable-Colours-Colour-Wheel-228c75be83d34b5c8dab0306a4717a0b

# Changes Made In This PR

- Replaced colour picker with colour wheel

# Screenshots

_for UI changes, show a before and after shot_\
**Before:**
<img width="330" alt="Screenshot 2022-02-04 at 12 43 11 AM" src="https://user-images.githubusercontent.com/71954278/152625438-4ede4663-e796-4eb0-883d-57d81bbae2db.png">

**After:**
<img width="309" alt="Screenshot 2022-02-04 at 12 42 11 AM" src="https://user-images.githubusercontent.com/71954278/152625450-58a59787-a97e-4e0a-80ca-9dc440bc0814.png">

2022-02-05 05:42 UTC, millasml requested changes
this looks good, but i think it doesnt have the full functionality

- i believe raei suggested using one of the square ones because with this color wheel, black isn't an option
- we also want the color wheel to be applicable to all the different fields (e.g. for text and background), so based on which part is selected you update the different colour

2022-02-06 16:03 UTC, millasml reviewed
looking great! just one last small thing - do you think you can make some indicator of which field is the selected one, by styling the border of the field to be solid black (like the style it is when you click on it)

2022-02-06 16:03 UTC, millasml commented on src/components/builder/left/sections/Colors.js
> +        onClick={(e) => handleChange(e)}
i think things get complicated because we are trying to use the Input from `shared`. Instead, lets create another component called `ColorInput`, and then use that here. I hope this make things easier!

2022-02-12 07:28 UTC, tharshita commented
ok done! Rn the input already has a border when clicked by the use of path instead of switch cases, is this approach still ok?

2022-02-14 00:44 UTC, millasml requested changes
this comes pretty close, but one issue is that when i switch the field that needs to be updated, the color wheel doesn't update to the previous value of that field. 

i.e. lets say right now primary color is selected at #abcdef, and text color is #123456. The color wheel now is at #abcdef cause I just set the primary color. If i select text color next, what I would expect is that the color wheel will now have #123456. But instead, it stays at #abcdef

2022-02-14 00:44 UTC, millasml commented on src/components/builder/left/sections/Colors.js
> +          className={styles.circle}
remove this line

2022-02-14 00:44 UTC, millasml commented on src/components/builder/left/sections/Colors.js
> +          style={{ marginLeft: 20, marginBottom: 280 }}
remove this line too. If you remove the circles class name the colour picker should turn out nicely. you'd just have to center it

2022-02-14 00:48 UTC, millasml commented
also the diff in your package-lock.json seems a bit long. Did you upgrade to npm 8.3.0?

2022-02-15 03:40 UTC, millasml approved these changes

2022-02-17 11:04 UTC, raeiho approved these changes

2022-02-17 12:39 UTC, merged